# ============================================================================
# test_shape_gradient_3d.jl — FD-validate the 3D discrete adjoint (interior-only).
#
# A small 3D elastic block.  The point cloud is generated by WhatsThePoint
# (irregular volume fill via SlakKosec), NOT a hand-built Cartesian lattice:
#   - a regular lattice is polynomial-unisolvency-degenerate at poly_deg=3, so
#     the local RBF saddle systems go singular and `_build_weights` throws;
#   - WTP's irregular fill is unisolvent by construction and better-conditioned.
#
# BCs are all-boundary Dirichlet, clamped to a manufactured linear stretch field.
# This keeps the forward problem WELL-POSED (every boundary node has a real BC —
# applying the interior PDE at an unconstrained boundary node makes A near-singular
# and the adjoint/FD comparison meaningless).  The adjoint is validated against
# central FD of the SAME discrete problem regardless of the field's physics.
#
# Run:  jlrun plate_with_hole/test_shape_gradient_3d.jl   (from examples/)
# ============================================================================
using Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

using Macchiato
using WhatsThePoint
import WhatsThePoint as WTP
import RadialBasisFunctions: find_neighbors
using RadialBasisFunctions: PHS
using StaticArrays, LinearAlgebra, Printf
using Unitful: m, ustrip

# ---- small 3D block ---------------------------------------------------------
const Lx, Ly, Lz = 0.6, 0.4, 0.3
const Δ  = 0.1                      # target spacing
const k  = 50                       # 3D poly_deg=3 → C(6,3)=20 monomials; k≈2.5× over

model = LinearElasticity3D(E = 1.0e7, ν = 0.3)
basis = PHS(3; poly_deg = 3)

# ---- WTP cloud: box surface → irregular volume fill -------------------------
# Build the 6 box faces as a point surface with outward normals, then let WTP
# fill the interior.  Boundary points form a face grid; the volume is irregular.
function box_surface(hx, hy, hz, Δ)
    pts = WTP.Point[]; nrm = SVector{3,Float64}[]
    seen = Set{NTuple{3,Int}}()
    key(x, y, z) = (round(Int, x/Δ*1e3), round(Int, y/Δ*1e3), round(Int, z/Δ*1e3))
    add(x, y, z, n) = (k0 = key(x,y,z); k0 in seen || (push!(seen, k0);
                       push!(pts, WTP.Point(x*m, y*m, z*m)); push!(nrm, n)))
    rng(h) = range(-h, h; length = max(2, round(Int, 2h/Δ) + 1))
    for x in rng(hx), y in rng(hy)
        add(x, y, +hz, SVector(0.0,0.0,1.0)); add(x, y, -hz, SVector(0.0,0.0,-1.0))
    end
    for x in rng(hx), z in rng(hz)
        add(x, +hy, z, SVector(0.0,1.0,0.0)); add(x, -hy, z, SVector(0.0,-1.0,0.0))
    end
    for y in rng(hy), z in rng(hz)
        add(+hx, y, z, SVector(1.0,0.0,0.0)); add(-hx, y, z, SVector(-1.0,0.0,0.0))
    end
    areas = fill(Δ^2 * m^2, length(pts))
    return PointBoundary(identity.(pts), nrm, areas), length(pts)  # narrow Vector{Point} eltype
end

bnd_surf, n_surf = box_surface(Lx/2, Ly/2, Lz/2, Δ)
cloud = WTP.discretize(bnd_surf, ConstantSpacing(Δ * m); alg = SlakKosec())

svec(p) = (c = WTP.coords(p); SVector{3,Float64}(ustrip(c.x), ustrip(c.y), ustrip(c.z)))
vol_pts = svec.(WTP.points(cloud.volume))
bnd_pts = svec.(WTP.points(cloud.boundary))
pts = vcat(vol_pts, bnd_pts)
N = length(pts)
n_int = length(vol_pts)
interior_idx = collect(1:n_int)
boundary_idx = collect((n_int+1):N)
@printf("WTP cloud: %d volume + %d boundary = %d total\n", n_int, length(bnd_pts), N)

adjl = find_neighbors(pts, k)

# ---- all-boundary Dirichlet, clamped to a manufactured linear stretch -------
# u = (c·x, -ν c·y, -ν c·z) — exact homogeneous-Navier solution (linear ⇒ 0 2nd
# derivative).  Any smooth field validates the adjoint; this one also makes the
# forward solve recover the field to machine precision.
const cstr = 0.01
dirichlet_dofs = Int[]; dirichlet_vals = Float64[]
for i in boundary_idx
    p = pts[i]
    push!(dirichlet_dofs, i);      push!(dirichlet_vals,  cstr * p[1])
    push!(dirichlet_dofs, i + N);  push!(dirichlet_vals, -model.ν * cstr * p[2])
    push!(dirichlet_dofs, i + 2N); push!(dirichlet_vals, -model.ν * cstr * p[3])
end
active = let a = trues(3N); for d in dirichlet_dofs; a[d] = false; end; a end
interior_rows = let r = falses(N); for i in interior_idx; r[i] = true; end; r end
@printf("Dirichlet DOFs: %d  (all %d boundary nodes, 3 comps each)\n",
        length(dirichlet_dofs), length(boundary_idx))

# ---- forward solve + gradient helpers ---------------------------------------
flat3(P) = reduce(vcat, [[p[1], p[2], p[3]] for p in P])

function compliance(pts_flat)
    res = shape_gradient_3d(pts_flat, model, N, adjl, basis, active,
                            dirichlet_dofs, dirichlet_vals, identity;
                            interior_rows = interior_rows)
    return dot(res.u, res.u) / 2
end
function compliance_grad(pts_flat)
    res = shape_gradient_3d(pts_flat, model, N, adjl, basis, active,
                            dirichlet_dofs, dirichlet_vals, u -> u;   # ∂L/∂u = u
                            interior_rows = interior_rows)
    return res.Δpts
end

# ---- FD validation ----------------------------------------------------------
println("\nFD validation — shape_gradient_3d vs central FD:")
g_ad = compliance_grad(flat3(pts))
hh = 1.0e-6

probe = vcat(1:5, (n_int÷2):(n_int÷2+3), (N-3):N)
ratios = Float64[]
@printf("  %4s %3s  %13s %13s %12s\n", "pt", "c", "AD", "FD", "|AD|/|FD|")
for i in probe, c in 1:3
    δ = zeros(3N); δ[3i - 3 + c] = hh
    fd_val = (compliance(flat3(pts) + δ) - compliance(flat3(pts) - δ)) / (2hh)
    ad_val = g_ad[3i - 3 + c]
    if abs(fd_val) > 1e-8           # skip near-zero entries (ratio ill-defined)
        push!(ratios, abs(ad_val) / abs(fd_val))
    end
    @printf("  %4d  %1d   %+13.6e %+13.6e %12.6f\n",
            i, c, ad_val, fd_val, abs(ad_val) / max(abs(fd_val), 1e-30))
end

med_ratio = sort(ratios)[max(1, length(ratios) ÷ 2)]
n_good = count(r -> abs(r - 1.0) < 0.05, ratios)
println("\n--- Summary ---")
@printf("  median |AD|/|FD| = %.6f   (over %d entries with |FD|>1e-8)\n", med_ratio, length(ratios))
@printf("  within 5%% of 1.0: %d / %d\n", n_good, length(ratios))
if abs(med_ratio - 1.0) < 0.02
    println("  ✓ shape_gradient_3d VALIDATED (interior-only, Dirichlet BCs)")
else
    println("  ✗ DISCREPANCY — inspect")
end
